version: "3.8"

services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile.macos.m1
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server/:/usr/src/app/
      - ./audio/:/usr/audio/
    ports:
      - 8000:8000
    env_file:
      - ./.env
